apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: openim-istio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https-openim-api
      protocol: HTTPS
    tls:
      mode: SIMPLE                          
      credentialName: myk8s-magiclab396-credential 
    hosts:
    - "*" 
  - port:
      number: 443
      name: https-openim-mgmt-chat
      protocol: HTTPS
    tls:
      mode: SIMPLE                          
      credentialName: myk8s-magiclab396-credential 
    hosts:
    - "chat-openim.k8s.magiclab396.com"  
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openim-api
spec:
  hosts:
  - openim.k8s.magiclab396.com
  gateways:
  - openim-istio-gateway
  http:
  # - match:
  #   # - uri:
  #   #     exact: /productpage
  #   - uri:
  #       prefix: /
  #   route:
  #   - destination:
  #       host: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
  #       port:
  #         number: 9090
  #   - uri:
  #       exact: /login
  #   - uri:
  #       exact: /logout
  #   - uri:
  #       prefix: /api/v1/products
    #  - match:
    #     - uri:
    #         prefix: /
    #    route:
    #     - destination:
    #         host: productpage
    #         port:
    #           number: 9080
    
    - route:
        - destination:
            host: api.openim.svc.cluster.local
            port:
              number: 10002
    # - route:
    #     - destination:
    #         host: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
    #         port:
    #           number: 9090

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openim-msg-gateway
spec:
  hosts:
  - "openim-gateway.k8s.magiclab396.com"
  gateways:
  - openim-istio-gateway
  http:
    - route:
      - destination:
          host: msg-gateway.openim.svc.cluster.local
          port:
            number: 10001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openim-mgmt-chat
spec:
  hosts:
  - "chat-openim.k8s.magiclab396.com"
  gateways:
  - openim-istio-gateway
  http:
    - route:
      - destination:
          host: management-api-chat.openim-management.svc.cluster.local
          port:
            number: 10008

# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: dashboard
# spec:
#   hosts:
#   - "myk8s.dashboard.magiclab396.com"
#   gateways:
#   - bookinfo-gateway
#   http:
#   # - match:
#   #   - uri:
#   #       exact: /productpage
#   #   - uri:
#   #       prefix: /static
#   #   - uri:
#   #       exact: /login
#   #   - uri:
#   #       exact: /logout
#   #   - uri:
#   #       prefix: /api/v1/products
#     - route:
#       - destination:
#           host: my-k8s-dashboard-kubernetes-dashboard.k8s-dashboard.svc.cluster.local
#           port:
#             number: 443
