apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kube-prometheus-app
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: system-project
  sources: 
    - chart: kube-prometheus-stack
      repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 51.2.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
         - $values/system/kube-prometheus/values.yaml
    - repoURL: "https://github.com/truongpx396/OpenIM-K8S-Deployment.git"
      ref: values
      targetRevision: main

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true