apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-project
  namespace: argocd
spec:
  description: System Project
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'